<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2024/06/19 10:50:31

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:host=localhost;dbname=jobeet_test',
  'username' => 'root',
  'password' => 'servir',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
